### ISSUE TITLE
could you show the train dataset format, such as the source.txt, source.xls, target.txt, target.xls？

### ISSUE THREAD

**Issue by zsrluminous** [cpf0079/UCDA#2]

**Comment by cpf0079** [comment]
Of course. What are recorded in source.txt/target.txt are their numbers in the datasets, such as 1,2,3,4,...
And their corresponding probability distributions of qulity are recored in source.xls/target.xls, such as line 1(no. 1): 0.1,0.3,0.2,0.3,0.1. These five numbers stand for the probabilities of score 1, 2, 3, 4 and 5.

**Comment by zsrluminous** [comment]
ok, i have another question, i download the LBVD dataset, and the given  LBVD_SUBJECTIVEDATA.CSV provide the mos value and varience like this :
3.96 | 0.195959
3.28 | 0.53066

how can i get the labels of quality rating distributions saied in your paper?

**Comment by cpf0079** [comment]
I have uploaded the raw_score.xlsx in the repository, you can get the distribution information from it.
