### ISSUE TITLE
the domain loss reduced to 1.3863 and then not changed, what is the probably reason for this result?

### ISSUE THREAD

**Issue by zsrluminous** [cpf0079/UCDA#3]
hi，when i trian the model, the domain loss is reduced to 1.3863, and then did not changed after 1 epoch，the total loss is also not changed,   the train loss is as follows:
 Epoch [16/60], Step [100/1329], Loss: 1.1091, Class_loss: 0.0001, Domain_loss: 1.3863
Epoch [16/60], Step [110/1329], Loss: 1.1091, Class_loss: 0.0001, Domain_loss: 1.3863
Epoch [16/60], Step [120/1329], Loss: 1.1091, Class_loss: 0.0000, Domain_loss: 1.3863
Epoch [16/60], Step [130/1329], Loss: 1.1091, Class_loss: 0.0000, Domain_loss: 1.3863
Epoch [16/60], Step [140/1329], Loss: 1.1092, Class_loss: 0.0001, Domain_loss: 1.3863

and when i test the model, all the image output  is the same,  what is the probably reason for this result?

thanks for your hard work, look forwarding to your answer

**Comment by cpf0079** [comment]
Do u use the default config during training?

**Comment by zsrluminous** [comment]
no,  i  replace the C3D backbone to resnet50，because i train the IQA task，other config like lr etc,  i  use the default

**Comment by zsrluminous** [comment]
when you train the model , will the domain loss reduce to 1.3863 and then do not change?    (the 1.3863 seems mean the probability of  predicting source domain or target  domain is the nearly same?)

**Comment by cpf0079** [comment]
It seems like that the domain classfier fails to take actions, and I had not encountered this problem.
Which database you used as the source domain since you targeted on the IQA task?

**Comment by zsrluminous** [comment]
i use the koniq-10k dataset，  when you train the VQA model,  How much will the final loss ，domain loss and the class loss fall ?

**Comment by zsrluminous** [comment]
我看论文里是说训练的域分类器的优化目标是最终分不出输入图像是源域还是目标域，这样特征空间就对齐了，那是不是说 最终当每次域分类器预测输入图像是源域还是目标域的概率均为0.5的时候，说明源域和目标域已经区分不了了？ 而当概率均为0.5的时候，计算的domain loss  NLLLoss值就为1.3863

**Comment by cpf0079** [comment]
Yes, when the domain classifier is well trained, the domain loss would tend to converge to a fixed value.
The adaptation performance largely depends on the source/target domain you choose. I have tried IQA tasks before, but regretfully, I also failed.

**Comment by zsrluminous** [comment]
那意思是域自适应的方法与数据集强相关吗，或者该方法只对VQA有效 而 IQA您之前尝试效果也是不ok吗，您知道可能的原因是什么吗？  非常感谢

**Comment by cpf0079** [comment]
Based on the fact that deep learning is data-driven, I largely think the the data itself is the problem. As for how to solve it, I suggest you to try to modify the adaptation component instead of directly deploying the original one.

**Comment by zsrluminous** [comment]
ok,  thank you  very much

**Comment by cpf0079** [comment]
You're always welcome.
